#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include <net/if.h>
#include <bpf/libbpf.h>
// This header will be automatically generated by bpftool during the build process
#include "xdp_ips.skel.h" 

static volatile bool exiting = false;

static void sig_handler(int sig) {
    exiting = true;
}

int main(int argc, char **argv) {
    struct xdp_ips_bpf *skel;
    int err = 0;
    int ifindex;

    if (argc < 2) {
        fprintf(stderr, "Usage: %s <ifname>\n", argv[0]);
        return 1;
    }

    ifindex = if_nametoindex(argv[1]);
    if (!ifindex) {
        fprintf(stderr, "Failed to get ifindex of %s\n", argv[1]);
        return 1;
    }

    /* Open and load the compiled BPF skeleton */
    skel = xdp_ips_bpf__open_and_load();
    if (!skel) {
        fprintf(stderr, "Failed to open and load BPF skeleton\n");
        return 1;
    }

    /* Attach XDP program to the specified interface */
    skel->links.xdp_drop_all = bpf_program__attach_xdp(skel->progs.xdp_drop_all, ifindex);
    if (!skel->links.xdp_drop_all) {
        fprintf(stderr, "Failed to attach XDP program to %s\n", argv[1]);
        err = -1;
        goto cleanup;
    }

    signal(SIGINT, sig_handler);
    signal(SIGTERM, sig_handler);

    printf("Successfully attached XDP program to %s.\n", argv[1]);
    printf("Dropping all traffic... Press Ctrl-C to stop.\n");

    /* Keep the user-space program running so the link stays active */
    while (!exiting) {
        sleep(1);
    }

cleanup:
    /* This automatically detaches the XDP program and frees resources */
    xdp_ips_bpf__destroy(skel);
    printf("\nDetached XDP program and cleaned up.\n");
    return err < 0 ? -err : 0;
}