#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include <net/if.h>
#include <arpa/inet.h>
#include <bpf/libbpf.h>
#include <bpf/bpf.h>
#include <time.h>
// This header is generated by bpftool based on the BPF program and contains skeleton definitions
#include "xdp_ips.skel.h"

static volatile bool exiting = false;

static void sig_handler(int sig) {
    exiting = true;
}

// Helper to format IP addresses
void format_ip(__u32 ip, char *buf) {
    struct in_addr addr;
    addr.s_addr = ip;
    inet_ntop(AF_INET, &addr, buf, INET_ADDRSTRLEN);
}

// Week 5 Milestone: Monitoring and Metrics
void poll_blocklist(int map_fd) {
    __u32 key = 0, next_key;
    __u64 value;
    char ip_str[INET_ADDRSTRLEN];
    int active_blocks = 0;

    // 1. Get standard time for the UI header
    time_t now_wall = time(NULL);
    struct tm *tm_info = localtime(&now_wall);
    char time_buf[26];
    strftime(time_buf, 26, "%Y-%m-%d %H:%M:%S", tm_info);

    // 2. Get kernel monotonic time for expiration math
    // This perfectly matches bpf_ktime_get_ns() used in the kernel
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    __u64 now_ns = ts.tv_sec * 1000000000ULL + ts.tv_nsec;

    printf("\033[2J\033[H");
    printf("========================================================\n");
    printf(" Vasi: XDP Intrusion Prevention System | %s\n", time_buf);
    printf("========================================================\n");
    printf(" %-20s | %s\n", "Source IP Address", "Status");
    printf("--------------------------------------------------------\n");

    // Iterate through the BPF map
    while (bpf_map_get_next_key(map_fd, &key, &next_key) == 0) {
        if (bpf_map_lookup_elem(map_fd, &next_key, &value) == 0) {
            
            if (now_ns > value) {
                // GARBAGE COLLECTION: The block expired, but no new 
                // packets arrived to trigger the kernel's cleanup.
                // We delete it from user-space so the UI is accurate.
                bpf_map_delete_elem(map_fd, &next_key);
            } else {
                format_ip(next_key, ip_str);
                printf(" %-20s | \033[31mBLOCKED\033[0m\n", ip_str);
                active_blocks++;
            }
        }
        key = next_key;
    }
    
    if (active_blocks == 0) {
        printf(" %-20s | \033[32mSECURE\033[0m\n", "No active threats");
    }
    printf("========================================================\n");
    printf(" Active Mitigations: %d\n", active_blocks);
    printf(" Press Ctrl+C to detach IPS and exit.\n");
    
    fflush(stdout); 
}

int main(int argc, char **argv) {
    struct xdp_ips_bpf *skel;
    int err = 0, ifindex;

    if (argc < 2) {
        fprintf(stderr, "Usage: %s <ifname>\n", argv[0]);
        return 1;
    }

    ifindex = if_nametoindex(argv[1]);
    if (!ifindex) {
        fprintf(stderr, "Failed to get ifindex of %s\n", argv[1]);
        return 1;
    }

    // Week 4 Milestone: User-Space Management
    skel = xdp_ips_bpf__open_and_load();
    if (!skel) {
        fprintf(stderr, "Failed to open and load BPF skeleton\n");
        return 1;
    }

    skel->links.xdp_ips_main = bpf_program__attach_xdp(skel->progs.xdp_ips_main, ifindex);
    if (!skel->links.xdp_ips_main) {
        fprintf(stderr, "Failed to attach XDP program\n");
        err = -1;
        goto cleanup;
    }

    signal(SIGINT, sig_handler);
    signal(SIGTERM, sig_handler);

    printf("IPS loaded on %s. Enforcing thresholds (SYN:100/s, ICMP:50/s, UDP:200/s).\n", argv[1]);

    int blocklist_fd = bpf_map__fd(skel->maps.blocklist);

    // Monitoring loop
    while (!exiting) {
        poll_blocklist(blocklist_fd);
        sleep(2);
    }

cleanup:
    xdp_ips_bpf__destroy(skel);
    printf("\nIPS detached successfully.\n");
    return err < 0 ? -err : 0;
}